### ISSUE TITLE
Using PGI as a host compiler not working with the latest Kokkos

### ISSUE THREAD

**Issue by guangyechen** [kokkos/nvcc_wrapper#27]
Using nvcc_wrapper with PGI 17.10 on X86(+gpu) does not work with the latest Kokkos (master branch, commit 5d6e7fb). I got the following error messages:
```
/projects/opt/centos7/pgi/linux86-64/17.10/include-gcc48/bits/c++config.h(190): error: identifier "nullptr" is undefined

/projects/opt/centos7/pgi/linux86-64/17.10/include-gcc48/bits/c++config.h(190): error: expected a ";"

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h(432): error: identifier "nullptr" is undefined

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h(432): error: expected a ";"

```

**Comment by ibaned** [comment]
@crtrott @dsunder @dhollman 

If `nullptr` is not defined, it seems to me like this compiler does not support C++11. Are you sure you're using the C++ compiler and that it is receiving the `-std=c++11` flag?

**Comment by ibaned** [comment]
Note also that these warnings are from the compiler's header files themselves, this seems very unrelated to Kokkos.

**Comment by nmhamster** [comment]
@ibaned - this doesn't seem to work on White with PGI 19.3.0. For some reason, I seem to be able to compile fine using PGI 19.3.0 when I am compiling only for the host. When I use `nvcc_wrapper` set to use PGI for host compilation, the build fails and seems to use the RedHat supplied C++ files rather than the paths provided in `localrc` when we install the PGI compiler (which point to GCC 7.2.0 on our machines). This is super weird - wonder if this is something to do with NVCC getting in the way.

**Comment by nmhamster** [comment]
@ibaned - I even tried manually specifying the include paths and this didn't work either.

**Comment by ibaned** [comment]
@nmhamster I don't ever use PGI so I'm not sure how helpful I can be, but maybe the way to start debugging this would be to directly run the `nvcc` command that `nvcc_wrapper` puts together, and use a non-Kokkos reproducer that just uses some C++11 features like `nullptr`. That would remove any connection to Kokkos and really focus on the real issue which is how to install and use `nvcc`+PGI.

**Comment by crtrott** [comment]
I can reproduce this on white. I am using PGI 19.3 and NVCC 10.1 with this line:
```
~/Kokkos/kokkos/generate_makefile.bash --with-cuda --arch=Power8,Pascal60 --cxxflags="-O3 -ccbin pgc++" --ldflags="-O3 -ccbin pgc++" --compiler=/home/crtrott/Kokkos/kokkos/bin/nvcc_wrapper --cxxstandard=c++14
```
Taking the localrc from the bin directory of the pgi compiler (i.e. the `which pgc++` directory) and copying it into `${HOME}/.mypgcpprc` fixes the issue (after commenting out the two lines for the license its still getting from localrc I guess). I think that shouldn't be necessary though should it??

**Comment by mcolg** [comment]
In the OP, the problem there is due to the use of GNU 4.8.5 on the system given GNU didn't fully support C++11 until 4.9.3.  When PGI switched pgc++ to be object compatible with GNU, it made it so we need to rely on the GNU STL so the C++ standard level we support is also tied to the level the GNU's STL supports.

The compiler configuration information as to which GNU install to use is contained in a file called "localrc" in the PGI bin directory.  In a network install, a unique "localrc.<hostname>" file is created for a system upon first use of the compilers.  For a single system install, the localrc is created at installation.   

On x86, we include a script called "addlocalrc", which will attempt to find all GNU installations on a system and create a unique localrc file for each GNU version.  Users can then use the environment variable "PGI_LOCALRC" to indicate which localrc file to use.  This is particularly useful for use with system's using modules so system admins can point to different localrc files depending upon the modules being used.

As Christian did, users can override the PGI configuration files.  However, users can also create their own localrc files by running the command "makelocalrc -x -d . -gcc /full/path/to/bin/gcc -gpp  /full/path/to/bin/g++ -g77 /full/path/to/bin/gfortran".  A localrc file will be created in the local directory. 
 Then optionally rename the localrc file and set PGI_LOCALRC to point to this file.  I personally use this method to easily switch between the GNU STLs I want to use.

As for the issue Si is seeing on White, I'm not sure.  I suspect White's localrc file might not be configured to use GNU 7.3.0, but that's unclear.  I just did a Kokkos build on Power using GNU 7.3.0, PGI 19.3, and CUDA 10.1, and did not see any issues.  My PGI_LOCALRC environment variable pointed to a localrc configured to use GNU 7.3.0.

**Comment by crtrott** [comment]
@mcolg the problem is that the localrc in the bin directory of the PGI compiler is not getting picked up. I simply copied that file from there into my own directory - without changing any info with respect to where to find GCC - and that fixed my issue. This only appears to be a problem when using NVCC which calls PGI, PGI on its own is fine.

**Comment by mcolg** [comment]
I'm not sure why this would be the case here.  pgc++ will look in it's bin directory for the localrc file and shouldn't matter if pgc++ is invoked from within nvcc.  

Can you try running nvcc_wrapper with "-dryrun" so we can see which rcfiles it's picking up?  i.e. "nvcc_wrapper -dryrun -ccbin pgc++ x.cpp"

**Comment by crtrott** [comment]
```
/home/crtrott/Kokkos/kokkos/bin/nvcc_wrapper  -I./ -I/ascldap/users/crtrott/Kokkos/kokkos/core/src -I/ascldap/users/crtrott/Kokkos/kokkos/containers/src -I/ascldap/users/crtrott/Kokkos/kokkos/algorithms/src -I/ascldap/users/crtrott/Kokkos/kokkos/core/src/eti --c++14 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -arch=sm_60 -I/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/include -I/ascldap/users/crtrott/Kokkos/kokkos/tpls/gtest -I/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test -O3 -ccbin pgc++  -c /ascldap/users/crtrott/Kokkos/kokkos/core/unit_test/UnitTestMainInit.cpp --dryrun
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin
#$ _THERE_=/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/ppc64le-linux
#$ TOP=/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/..
#$ NVVMIR_LIBRARY_DIR=/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../lib:/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/extras/CUPTI/lib64:/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/lib64:/home/projects/ppc64le/pgi/compilers/2019/19.3.0/linuxpower/19.3/lib:/opt/lsf/10.1/linux3.10-glibc2.17-ppc64le/lib
#$ PATH=/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../nvvm/bin:/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin:/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin:/home/projects/ppc64le/pgi/compilers/2019/19.3.0/linuxpower/19.3/bin:/opt/lsf/10.1/linux3.10-glibc2.17-ppc64le/etc:/opt/lsf/10.1/linux3.10-glibc2.17-ppc64le/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin
#$ INCLUDES="-I/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../targets/ppc64le-linux/include"  
#$ LIBRARIES=  "-L/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../targets/ppc64le-linux/lib/stubs" "-L/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../targets/ppc64le-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ pgc++ -D__CUDA_ARCH__=600 -E --nvcchost -cppsuffix=cpp   -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  --c++14 -O3 -I"./" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/containers/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/algorithms/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/src/eti" -I"/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/include" -I"/ascldap/users/crtrott/Kokkos/kokkos/tpls/gtest" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test" "-I/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../targets/ppc64le-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=105 --preinclude "cuda_runtime.h" "/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test/UnitTestMainInit.cpp" > "/tmp/tmpxft_0000bdb4_00000000-6_UnitTestMainInit.cpp1.ii" 
#$ cicc --pgc++ --gnu_version=40805 --allow_managed --unsigned_chars  --diag_suppress=esa_on_defaulted_function_ignored  -arch compute_60 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "tmpxft_0000bdb4_00000000-2_UnitTestMainInit.fatbin.c" -tused -nvvmir-library "/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "/tmp/tmpxft_0000bdb4_00000000-3_UnitTestMainInit.module_id" --orig_src_file_name "/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test/UnitTestMainInit.cpp" --gen_c_file_name "/tmp/tmpxft_0000bdb4_00000000-5_UnitTestMainInit.cudafe1.c" --stub_file_name "/tmp/tmpxft_0000bdb4_00000000-5_UnitTestMainInit.cudafe1.stub.c" --gen_device_file_name "/tmp/tmpxft_0000bdb4_00000000-5_UnitTestMainInit.cudafe1.gpu"  "/tmp/tmpxft_0000bdb4_00000000-6_UnitTestMainInit.cpp1.ii" -o "/tmp/tmpxft_0000bdb4_00000000-5_UnitTestMainInit.ptx"
#$ ptxas -arch=sm_60 -m64  "/tmp/tmpxft_0000bdb4_00000000-5_UnitTestMainInit.ptx"  -o "/tmp/tmpxft_0000bdb4_00000000-7_UnitTestMainInit.sm_60.cubin" 
#$ fatbinary --create="/tmp/tmpxft_0000bdb4_00000000-2_UnitTestMainInit.fatbin" -64 -no-asm "--image=profile=sm_60,file=/tmp/tmpxft_0000bdb4_00000000-7_UnitTestMainInit.sm_60.cubin" "--image=profile=compute_60,file=/tmp/tmpxft_0000bdb4_00000000-5_UnitTestMainInit.ptx" --embedded-fatbin="/tmp/tmpxft_0000bdb4_00000000-2_UnitTestMainInit.fatbin.c" 
#$ rm /tmp/tmpxft_0000bdb4_00000000-2_UnitTestMainInit.fatbin
#$ pgc++ -E --nvcchost -cppsuffix=cpp  -D__CUDACC__ -D__NVCC__  --c++14 -O3 -I"./" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/containers/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/algorithms/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/src/eti" -I"/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/include" -I"/ascldap/users/crtrott/Kokkos/kokkos/tpls/gtest" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test" "-I/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../targets/ppc64le-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=105 --preinclude "cuda_runtime.h" "/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test/UnitTestMainInit.cpp" > "/tmp/tmpxft_0000bdb4_00000000-4_UnitTestMainInit.cpp4.ii" 
#$ cudafe++ --pgc++ --gnu_version=40805 --allow_managed --unsigned_chars  --diag_suppress=esa_on_defaulted_function_ignored --m64 --parse_templates --gen_c_file_name "/tmp/tmpxft_0000bdb4_00000000-5_UnitTestMainInit.cudafe1.cpp" --stub_file_name "tmpxft_0000bdb4_00000000-5_UnitTestMainInit.cudafe1.stub.c" --module_id_file_name "/tmp/tmpxft_0000bdb4_00000000-3_UnitTestMainInit.module_id" "/tmp/tmpxft_0000bdb4_00000000-4_UnitTestMainInit.cpp4.ii" 
#$ pgc++ -D__CUDA_ARCH__=600 -c --nvcchost -cppsuffix=cpp   -DCUDA_DOUBLE_MATH_FUNCTIONS --c++14 -O3 -I"./" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/containers/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/algorithms/src" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/src/eti" -I"/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/include" -I"/ascldap/users/crtrott/Kokkos/kokkos/tpls/gtest" -I"/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test" "-I/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/bin/../targets/ppc64le-linux/include"   --no_preincludes -o "UnitTestMainInit.o" "/tmp/tmpxft_0000bdb4_00000000-5_UnitTestMainInit.cudafe1.cpp"
```

**Comment by crtrott** [comment]
Here is how to solve my compilation issue:
```
-bash-4.2$ /home/crtrott/Kokkos/kokkos/bin/nvcc_wrapper  -I./ -I/ascldap/users/crtrott/Kokkos/kokkos/core/src -I/ascldap/users/crtrott/Kokkos/kokkos/containers/src -I/ascldap/users/crtrott/Kokkos/kokkos/algorithms/src -I/ascldap/users/crtrott/Kokkos/kokkos/core/src/eti --c++14 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -arch=sm_60 -I/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/include -I/ascldap/users/crtrott/Kokkos/kokkos/tpls/gtest -I/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test -O3 -ccbin pgc++  -c /ascldap/users/crtrott/Kokkos/kokkos/core/unit_test/UnitTestMainInit.cpp
/usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ppc64le-redhat-linux/bits/c++config.h(190): error: identifier "nullptr" is undefined
....
/usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/cmath(406): error: variable "std::constexpr" has already been defined

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_0000c1ed_00000000-6_UnitTestMainInit.cpp1.ii".
Compilation terminated.
-bash-4.2$ cp /home/projects/ppc64le/pgi/compilers/2019/19.3.0/linuxpower/19.3/bin/localrc ~/.mypgcpprc 
-bash-4.2$ sed -i 's|variable|#variable|g' ~/.mypgcpprc
-bash-4.2$ /home/crtrott/Kokkos/kokkos/bin/nvcc_wrapper  -I./ -I/ascldap/users/crtrott/Kokkos/kokkos/core/src -I/ascldap/users/crtrott/Kokkos/kokkos/containers/src -I/ascldap/users/crtrott/Kokkos/kokkos/algorithms/src -I/ascldap/users/crtrott/Kokkos/kokkos/core/src/eti --c++14 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -arch=sm_60 -I/home/projects/ppc64le-pwr8-nvidia/cuda/10.1.105/include -I/ascldap/users/crtrott/Kokkos/kokkos/tpls/gtest -I/ascldap/users/crtrott/Kokkos/kokkos/core/unit_test -O3 -ccbin pgc++  -c /ascldap/users/crtrott/Kokkos/kokkos/core/unit_test/UnitTestMainInit.cpp
-bash-4.2$ 
```

**Comment by mcolg** [comment]
The PGI flag is "-dryrun" not "--dryrun".  Can you try again with "-dryrun"?

From the output, I appears that GNU 4.8.5 is being used and hence the error.

**Comment by crtrott** [comment]
OK that found the issue. There is another localrc file (localrc.nodename) which it picks up. And that one points to the wrong gcc. Putting the user level file in has precedence since it picks that up later.

**Comment by crtrott** [comment]
And it also explains why our nightlies don't find that, since they run on the compute nodes they don't match the nodename and thus pick up the correct default localrc file.

**Comment by mcolg** [comment]
Great! Glad you were able to find the issue.

**Comment by ibaned** [comment]
Not an `nvcc_wrapper` issue, more of a nightmare of local config files associated with PGI.
